language: swift
osx_image: xcode9.3
script:
- xcodebuild clean test -workspace ./source/TravisBrowserstack.xcworkspace/ -scheme TravisBrowserstack  -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO  -quiet
